//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class drone_medication
    {
        public int id { get; set; }
        public int id_dron { get; set; }
        public int id_medicamento { get; set; }
    
        public virtual dron dron { get; set; }
        public virtual medication medication { get; set; }
    }
}
