//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dron
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dron()
        {
            this.drone_medication = new HashSet<drone_medication>();
        }
    
        public int id { get; set; }
        public string serial_number { get; set; }
        public int id_model { get; set; }
        public double weight_limit { get; set; }
        public int batery_capacity { get; set; }
        public int id_state { get; set; }
    
        public virtual model model { get; set; }
        public virtual state state { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<drone_medication> drone_medication { get; set; }
    }
}
