//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medication()
        {
            this.drone_medication = new HashSet<drone_medication>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public double weight { get; set; }
        public string code { get; set; }
        public byte[] image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<drone_medication> drone_medication { get; set; }
    }
}
