//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonsApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dronesEntities : DbContext
    {
        public dronesEntities()
            : base("name=dronesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dron> dron { get; set; }
        public virtual DbSet<drone_medication> drone_medication { get; set; }
        public virtual DbSet<medication> medication { get; set; }
        public virtual DbSet<model> model { get; set; }
        public virtual DbSet<state> state { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
